---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx-demo
spec:
  replicas: 3
  # revisionHistoryLimit
  # 限制最大保留的revision number
  revisionHistoryLimit: 15
  # minReadySeconds
  # Kubernetes在等待设置的时间后才进行升级
  # 如果没有设置该值，Kubernetes会假设该容器启动起来后就提供服务了
  # 如果没有设置该值，在某些极端情况下可能会造成服务服务不能正常运行
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # maxSurge
      # 升级过程中最多可以比原先设置多出的POD数量
      # 例如：maxSurage=1，replicas=5,则表示Kubernetes会先启动1一个新的Pod后才删掉一个旧的POD，
      # 整个升级过程中最多会有5 + 1个POD。
      maxSurge: 1
      # maxUnavaible
      # 升级过程中最多有多少个POD处于无法提供服务的状态
      # 当maxSurge不为0时，该值也不能为0
      # 例如：maxUnavaible=1，则表示Kubernetes整个升级过程中最多会有1个POD处于无法服务的状态。
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: nginxweb