version: '3'
services:
  mydb:
    image: mysql:latest
    container_name: wasm-echart-db
    restart: always
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/init/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    tty: true
  restapi:
    build:
      context: ./restapi
    restart: always
    volumes:
      - "./restapi:/workspace"
    container_name: wasm-echart-restapi
    ports:
      - "8081:8081"
    tty: true
    depends_on:
      - mydb
  # frontend:
  #   build:
  #     context: ./frontend
  #   platform: wasi/wasm32
  #   runtime: io.container.wasmedge.v1
  #   ports:
  #     - 8080:8080