version: '3'
services:
  mydb:
    image: mysql:latest
    container_name: pro-db
    restart: always
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/init/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
    tty: true