apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /home/shenyi/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: pv
              operator: In
              values:
                - local
