apiVersion: apps/v1
kind: Deployment
metadata:
  name: mygo
  namespace: myweb
spec:
  selector:
    matchLabels:
      app: mgo
  replicas: 1
  template:
    metadata:
      labels:
        app: mgo
    spec:
      containers:
        - name: mygo
          image: 172.17.70.145:5000/mygo:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mygo-service
  namespace: myweb
spec:
  selector:
    app: mgo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mygolb
  namespace: myweb
spec:
  rules:
    - host: api2.jtthink.com
      http:
        paths:
          - path: /
            backend:
              serviceName: mygo-service
              servicePort: 80

